name: 'CI/test and prepare release'
concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  pull_request_target:
    types:
      - closed

jobs:
  detect:
    runs-on: ubuntu-latest
    name: 'Detect pull request context'
    steps:
      - name: Check PR labels
        id: check_pr_label
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_DETAILS=$(gh pr view $PR_URL --json labels,changedFiles,files)
          echo "${PR_DETAILS}"
          # LABELS=$(echo "${PR_DETAILS}" | jq '.labels[]| select((.name=="minor") or (.name=="major") or (.name=="patch") or (.name=="no-release")) |.name')
          # NUMBER_OF_LABELS=$(echo "$LABELS" |wc -w)
          # if [ "$NUMBER_OF_LABELS" -eq "1" ] ; then
          #   echo "Found: $LABELS"
          #   echo "release-type=$LABELS" >> $GITHUB_OUTPUT
          # elif [ "$NUMBER_OF_LABELS" -gt "1" ] ; then
          #   echo "::error ::Too many release type labels: $( echo $LABELS | tr '\n' ' ' )"
          #   exit 1
          # else
          #   echo "::error ::No release type labels found(patch/minor/major/no-release)"
          #   exit 2
          # fi
